name: nix
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.nix'
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            sandbox = true
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check --all-systems
  nixfmt:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop --command nixfmt --check flake.nix
